### ISSUE TITLE
problem with rails 4.2.1.rc4

### ISSUE THREAD

**Issue by mostafa-zahran** [kazuhisa/hashed-jasper-rails#3]
I found this error when installing the gem on rails 4 but it works fine on rails 3
`bin/rake
Error:[rake --tasks] /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/activesupport-4.2.1.rc4/lib/active_support/dependencies.rb:274:in 'require': cannot load such file -- action_controller/metal/responder (LoadError)
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/activesupport-4.2.1.rc4/lib/active_support/dependencies.rb:274:in 'block in require'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/activesupport-4.2.1.rc4/lib/active_support/dependencies.rb:240:in 'load_dependency'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/activesupport-4.2.1.rc4/lib/active_support/dependencies.rb:274:in 'require'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/jasper-rails-1.0.3/lib/jasper-rails.rb:26:in '<top (required)>'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:76:in 'require'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:76:in 'block (2 levels) in require'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:72:in 'each'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:72:in 'block in require'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:61:in 'each'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:61:in 'require'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler.rb:134:in 'require'
    from /config/application.rb:30:in '<top (required)>'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application.rb:82:in 'require'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application.rb:82:in 'preload'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application.rb:143:in 'serve'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application.rb:131:in 'block in run'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application.rb:125:in 'loop'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application.rb:125:in 'run'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in '<top (required)>'
    from /home/mostafa/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in 'require'
    from /home/mostafa/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in 'require'
    from -e:1:in '<main>'
Error:[rake --prereqs] /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/activesupport-4.2.1.rc4/lib/active_support/dependencies.rb:274:in 'require': cannot load such file -- action_controller/metal/responder (LoadError)
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/activesupport-4.2.1.rc4/lib/active_support/dependencies.rb:274:in 'block in require'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/activesupport-4.2.1.rc4/lib/active_support/dependencies.rb:240:in 'load_dependency'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/activesupport-4.2.1.rc4/lib/active_support/dependencies.rb:274:in 'require'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/jasper-rails-1.0.3/lib/jasper-rails.rb:26:in '<top (required)>'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:76:in 'require'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:76:in 'block (2 levels) in require'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:72:in 'each'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:72:in 'block in require'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:61:in 'each'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:61:in 'require'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler.rb:134:in 'require'
    from config/application.rb:30:in '<top (required)>'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application.rb:82:in 'require'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application.rb:82:in 'preload'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application.rb:143:in 'serve'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application.rb:131:in 'block in run'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application.rb:125:in 'loop'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application.rb:125:in 'run'
    from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in '<top (required)>'
    from /home/mostafa/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in 'require'
    from /home/mostafa/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in 'require'
    from -e:1:in '<main>'`

**Comment by kazuhisa** [comment]
Hello @mostafa-zahran .

Thanks bug reports.
However, I think that a bug in the "jasper-rails.gem".
"hashed-jasper-rails" is dependent on "jasper-rails".
The incorporation of jasper-rails to Gemfile to try, the same error has occurred.

Unfortunately, there is no idea to solve the problem to me.

**Comment by mostafa-zahran** [comment]
I noticed you made a fork from jasper-rails which you use to depend on hashed-jasper-rails and I found there is a commit on the original repo handle this problem (which unfortunately reverted) so I was thinking in implement this commit on your's repo. 
what do you think?
https://github.com/fortesinformatica/jasper-rails/commit/af85d1ba0a014af58896086a330362ce966dd440

**Comment by mostafa-zahran** [comment]
sorry what I was said isn't true, what actually happen it you use version 1.0.3 and this is too old as version 2.0.0.beta2 is now available , anyway thanks for your response
